{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d52faa92",
   "metadata": {},
   "outputs": [],
   "source": [
    "##for TXLA\n",
    "\n",
    "from satpy import Scene, find_files_and_readers\n",
    "from pyresample import create_area_def\n",
    "from satpy.writers import get_enhanced_image\n",
    "from datetime import datetime\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from glob import glob\n",
    "from satpy import MultiScene\n",
    "\n",
    "def TXLAfigure(monthyear):\n",
    "    \n",
    "    i=0\n",
    "    base = '/home/hboi-ouri/Projects/RS_Files/TXLADailies/' + monthyear + '/MYD021KM.'\n",
    "\n",
    "    #files to be used\n",
    "    filenames = glob('/home/hboi-ouri/Projects/RS_Files/TXLADailies/' + monthyear + '/MYD021KM.*')\n",
    "    swats = np.unique([f.split('.')[1] for f in filenames])\n",
    "    \n",
    "    #area in the figure\n",
    "    extent = [-94, 27.5, -88, 30.5]\n",
    "    my_area = create_area_def('my_area', {'proj': 'lcc', 'lon_0': -91., 'lat_0': 29.5, 'lat_1': 29.5, 'lat_2': 29.5},\n",
    "                width=1500, height=750,\n",
    "                area_extent=extent, units='degrees')    \n",
    "        \n",
    "    fig =  plt.figure(figsize=(6, 4), dpi=400)\n",
    "\n",
    "    #loop\n",
    "    for swat in swats:\n",
    "        dayfiles = glob(base+swat+'*')\n",
    "        scn = Scene(dayfiles, reader='modis_l1b')\n",
    "        scn.load(['true_color'])\n",
    "\n",
    "        #reproject\n",
    "        new_scn = scn.resample(my_area)\n",
    "\n",
    "        #generate RGB from true color\n",
    "        rgb = get_enhanced_image(new_scn['true_color'])\n",
    "\n",
    "        #extract projection and lon lat from products\n",
    "        crs = new_scn['true_color'].attrs['area'].to_cartopy_crs()\n",
    "        lons, lats = new_scn['true_color'].attrs['area'].get_lonlats()\n",
    "\n",
    "        #true color\n",
    "        ax1 = plt.subplot(projection=crs)\n",
    "        rgb.data.plot.imshow(rgb='bands', transform=crs, ax=ax1)\n",
    "        \n",
    "        #title & save\n",
    "        ax1.set_title('MODISA_Mdelta_%s' % new_scn.start_time.isoformat())\n",
    "        fig.savefig('/home/hboi-ouri/Projects/NASA_Project/outputs/DailyImages/TXLA/MODISA_Mdelta_%s_rgb.png' % new_scn.start_time.isoformat())\n",
    "        fig.clear()\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "2df36a89",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 2400x1600 with 0 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 2400x1600 with 0 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "TXLAfigure('August2022')\n",
    "TXLAfigure('September2022')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fbf88c09",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "5f24dbad",
   "metadata": {},
   "outputs": [],
   "source": [
    "## For FLBay\n",
    "\n",
    "from satpy import Scene, find_files_and_readers\n",
    "from pyresample import create_area_def\n",
    "from satpy.writers import get_enhanced_image\n",
    "from datetime import datetime\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from glob import glob\n",
    "import cartopy.crs as ccrs\n",
    "import cartopy.feature as cfeature\n",
    "from satpy import MultiScene\n",
    "from satpy.multiscene import timeseries\n",
    "\n",
    "def FLBayfigure(monthyear):\n",
    "    \n",
    "    i=0\n",
    "    base = '/home/hboi-ouri/Projects/RS_Files/FLBayDailies/' + monthyear + '/MYD021KM.'\n",
    "\n",
    "    #files to be used\n",
    "    filenames = glob('/home/hboi-ouri/Projects/RS_Files/FLBayDailies/' + monthyear + '/MYD021KM.*')\n",
    "    swats = np.unique([f.split('.')[1] for f in filenames])\n",
    "    \n",
    "\n",
    "    #area in the figure\n",
    "    extent = [-82.0, 24.4, -80.0, 25.6]\n",
    "    my_area = create_area_def('my_area', {'proj': 'lcc', 'lon_0': -81.0, 'lat_0': 25.0, 'lat_1': 25.0, 'lat_2': 25.0},\n",
    "                    width=1500, height=750,\n",
    "                    area_extent=extent, units='degrees')\n",
    "        \n",
    "    fig =  plt.figure(figsize=(6, 4), dpi=400)\n",
    "\n",
    "    #loop\n",
    "    for swat in swats:\n",
    "        dayfiles = glob(base+swat+'*')\n",
    "        scn = Scene(dayfiles, reader='modis_l1b')\n",
    "        scn.load(['true_color'])\n",
    "\n",
    "        #reproject\n",
    "        new_scn = scn.resample(my_area)\n",
    "\n",
    "        #generate RGB from true color\n",
    "        rgb = get_enhanced_image(new_scn['true_color'])\n",
    "\n",
    "        #extract projection and lon lat from products\n",
    "        crs = new_scn['true_color'].attrs['area'].to_cartopy_crs()\n",
    "        lons, lats = new_scn['true_color'].attrs['area'].get_lonlats()\n",
    "\n",
    "        #left true color\n",
    "        ax1 = plt.subplot(projection=crs)\n",
    "        rgb.data.plot.imshow(rgb='bands', transform=crs, ax=ax1)\n",
    "\n",
    "        #title & save\n",
    "        ax1.set_title('MODISA_FLBay_%s' % new_scn.start_time.isoformat())\n",
    "        fig.savefig('/home/hboi-ouri/Projects/NASA_Project/outputs/DailyImages/FLBay/FLBay%s_rgb.png' % new_scn.start_time.isoformat())\n",
    "        fig.clear()\n",
    "        \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "bf85f2e4",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 2400x1600 with 0 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 2400x1600 with 0 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 2400x1600 with 0 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "FLBayfigure('July2022')\n",
    "FLBayfigure('August2022')\n",
    "FLBayfigure('September2022')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "20e0af33",
   "metadata": {},
   "outputs": [],
   "source": [
    "from satpy import Scene, find_files_and_readers\n",
    "from pyresample import create_area_def\n",
    "from satpy.writers import get_enhanced_image\n",
    "from datetime import datetime\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from glob import glob\n",
    "import cartopy.crs as ccrs\n",
    "import cartopy.feature as cfeature\n",
    "from satpy import MultiScene\n",
    "from satpy.multiscene import timeseries\n",
    "\n",
    "def TXLAfigure(monthyear):\n",
    "    \n",
    "    i=0\n",
    "    base = '/home/hboi-ouri/Projects/RS_Files/TXLADailies/' + monthyear + '/MYD021KM.'\n",
    "\n",
    "    filenames = glob('/home/hboi-ouri/Projects/RS_Files/TXLADailies/' + monthyear + '/MYD021KM.*')\n",
    "    swats = np.unique([f.split('.')[1] for f in filenames])\n",
    "    \n",
    "    extent = [-94, 27.5, -88, 30.5]\n",
    "    my_area = create_area_def('my_area', {'proj': 'lcc', 'lon_0': -91., 'lat_0': 29.5, 'lat_1': 29.5, 'lat_2': 29.5},\n",
    "                width=1500, height=750,\n",
    "                area_extent=extent, units='degrees')    \n",
    "        \n",
    "    fig =  plt.figure(figsize=(6, 4), dpi=400)\n",
    "\n",
    "    for swat in swats:\n",
    "        dayfiles = glob(base+swat+'*')\n",
    "        scn = Scene(dayfiles, reader='modis_l1b')\n",
    "        scn.load(['true_color'])\n",
    "\n",
    "        new_scn = scn.resample(my_area)\n",
    "\n",
    "        rgb = get_enhanced_image(new_scn['true_color'])\n",
    "\n",
    "        crs = new_scn['true_color'].attrs['area'].to_cartopy_crs()\n",
    "        lons, lats = new_scn['true_color'].attrs['area'].get_lonlats()\n",
    "\n",
    "        ax1 = plt.subplot(projection=crs)\n",
    "        rgb.data.plot.imshow(rgb='bands', transform=crs, ax=ax1)\n",
    "        \n",
    "        ax1.set_title('MODISA_Mdelta_%s' % new_scn.start_time.isoformat())\n",
    "        fig.savefig('/home/hboi-ouri/Projects/NASA_Project/outputs/DailyImages/TXLA/MODISA_Mdelta_%s_rgb.png' % new_scn.start_time.isoformat())\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
